apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  template:
    spec:
      serviceAccountName: backstage
      volumes:
        - name: backstage-config
          projected:
            sources:
              - secret:
                  name: integrations
                  items:
                    - key: github-integration.yaml
                      path: github-integration.yaml
              - configMap:
                  name: backstage-config
                  items:
                    - key: app-config.yaml
                      path: app-config.yaml
      containers:
        - name: backstage
          image: public.ecr.aws/m8u6z8z4/manabu-test:backstage-v0.0.4
          command:
            - node
            - packages/backend
            - --config
            - config/app-config.yaml
          volumeMounts:
            - name: backstage-config
              mountPath: "/app/config"
              readOnly: true
          envFrom:
            - secretRef:
                name: backstage-env-vars
