apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      path: packages/backstage/dev/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
