apiVersion: v1
kind: Secret
metadata:
  name: backstage-env-vars
  namespace: backstage
stringData:
  BACKSTAGE_FRONTEND_URL: http://localhost
  POSTGRES_HOST: postgresql.backstage.svc.cluster.local
  POSTGRES_PORT: '5432'
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ARGO_WORKFLOWS_URL: http://localhost
