apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: spark-operator
      repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
      targetRevision: 1.1.27
      helm:
        releaseName: spark-operator
        valueFiles:
          - $values/packages/spark-operator/dev/values.yaml
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: spark-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
