apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: ${ROLE_ARN}
  name: ${SA_NAME}
  namespace: ${NAMESPACE}

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ${SECRET_STORE_NAME}
  namespace: ${NAMESPACE}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: ${SA_NAME}
