apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: abc/abc:abc
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgresql-config
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
    - name: backend
      port: 7007
      targetPort: 7007
