apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  sources:
    - chart: argo-workflows
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.31.0
      helm:
        releaseName: argo-workflows
        valueFiles:
          - $values/packages/argo-workflows/dev/values-no-sso.yaml
    - repoURL: ${GITHUB_URL}
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-workflows
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
